from ...core.helpers.password_generator import gen_passwd
from ...tests.BaseTest import BaseTest
from ...pages.Pages import Pages


class TestPasswordRecoveryFlow(BaseTest):
    """
    ----------
    Test Scenario:
    ----------
    Preconditions:
    Email account: sanomatestemail@gmail.com and password: 123123qa

    Steps:
    1. Open {$url}
    2. Click on My Account button
    3. In login popup window click on "Wachtwoord vergeten?"
    4. Please fill the fields with with parameters:
        - E-mailadres: sanomatestemail@gmail.com
        - Wachtwoord = 123123qa
    5. Press the button "Doorgaan"
    6. Open Google account and check e-mail from "noreply@your-site.com via gigya-raas.com"
    7. Click "Reset Link"
    8. Fill the fields:
        - newPassword: <new password generated by gen_passwd()>
        - passwordRetype = newPassword
    9. Click "Wachtwoord wijzigen" button

    Expected Result:
    ----------------
    User seen "Wachtwoord wijzigen" message and password changed

    [FAIL]
     -  user can't see "Wachtwoord wijzigen"
    """

    EMAIL = "sanomatestemail@gmail.com"
    NEW_PASSWORD = gen_passwd()

    def test_password_recovery_flow(self, driver, status_item, url="https://gatekeeper.sanomaservices.nl/preview/sanomadefault/"):
        pages = Pages(driver)
        sanoma_default = pages.navigateTo().select_sanomadefault_login_page()
        sanoma_default.open_page(url)
        sanoma_default.click_account_button('login')
        sanoma_default.click_forgot_password()
        sanoma_default.send_password_to_e_mail(TestPasswordRecoveryFlow.EMAIL)
        sanoma_default.login_to_gmail(TestPasswordRecoveryFlow.EMAIL)
        sanoma_default.parse_email_and_reset_password(TestPasswordRecoveryFlow.NEW_PASSWORD)
        sanoma_default.open_page(url)
        sanoma_default.login_as_user(TestPasswordRecoveryFlow.EMAIL, TestPasswordRecoveryFlow.NEW_PASSWORD)
        assert sanoma_default.get_my_account_button_username() == "sanomatestemail", "New password doesn't apply"

